# 3. Engenharia de atributos e Extração de Insights

In [ ]:
# Extração da base de dados limpa com módulo 'data_cleaning.py'
import sys
import os

sys.path.append(os.path.abspath(".."))

import pandas as pd
import matplotlib.pyplot as plt
from src.data_cleaning import data_cleaning

df = pd.read_csv("../data/raw_data.csv")
df = data_cleaning(df)
df.head()

Inicializando limpeza dos dados...
Dados limpos com sucesso!

,ID_Pedido,Data_Compra,Cliente_ID,Produto,Categoria,Quantidade,Preco_Unitario,Status_Entrega
0,1001,2026-06-25,109,Smartwatch,Eletrônicos,1.0,5999.9,Cancelado
1,1002,2026-06-13,135,Smartwatch,Eletrônicos,3.0,8500.0,Entregue
2,1003,2026-06-05,113,Smartwatch,Acessórios,3.0,799.5,Entregue
3,1004,2026-06-20,130,Smartwatch,Acessórios,4.0,2100.0,Entregue
4,1005,2026-06-25,147,Smartwatch,Acessórios,4.0,850.0,Cancelado

In [4]:
# Feature Engineering: Criação de coluna 'Total_Venda'
df['Total_Venda'] = df['Quantidade'] * df['Preco_Unitario']

df.head()

,ID_Pedido,Data_Compra,Cliente_ID,Produto,Categoria,Quantidade,Preco_Unitario,Status_Entrega,Total_Venda
0,1001,2026-06-25,109,Smartwatch,Eletrônicos,1.0,5999.9,Cancelado,5999.9
1,1002,2026-06-13,135,Smartwatch,Eletrônicos,3.0,8500.0,Entregue,25500.0
2,1003,2026-06-05,113,Smartwatch,Acessórios,3.0,799.5,Entregue,2398.5
3,1004,2026-06-20,130,Smartwatch,Acessórios,4.0,2100.0,Entregue,8400.0
4,1005,2026-06-25,147,Smartwatch,Acessórios,4.0,850.0,Cancelado,3400.0

In [5]:
# Data Insight: Qual o total da receita?
total_venda = df['Total_Venda'].sum()
print(f"Receita total de vendas da loja: R${total_venda:,.2f}")

Receita total de vendas da loja: R$928,869.00

In [7]:
# Data Insight: Qual a receita total por categoria de produto?
receita_por_categoria = df.groupby('Categoria')['Total_Venda'].sum()
print("Receita total por categoria:")
receita_por_categoria

Receita total por categoria:

Categoria
Acessórios     195374.0
Eletrônicos    733495.0
Name: Total_Venda, dtype: float64

In [10]:
# Data Insight: Quais os produtos mais vendidos em quantidade?
produto_mais_vendido = df.groupby('Produto')['Quantidade'].sum().sort_values(ascending=False)
print("Total de unidades vendidas por quantidade: ")
produto_mais_vendido

Total de unidades vendidas por quantidade:

Produto
Smartphone          84.0
Fone de Ouvido      61.0
Smartwatch          59.0
Notebook            32.0
Teclado Mecânico    20.0
Name: Quantidade, dtype: float64

In [14]:
# Data Insight: quantidade de vendas realizadas por dia?
df_temporal = df.set_index('Data_Compra')

vendas_por_dia = df_temporal.resample('D')['Total_Venda'].sum()
print("Vendas realizadas por dia:")
vendas_por_dia

Vendas realizadas por dia:

Data_Compra
2026-06-05     2398.5
2026-06-06        0.0
2026-06-07        0.0
2026-06-08        0.0
2026-06-09    25500.0
               ...
2026-10-03        0.0
2026-10-04        0.0
2026-10-05        0.0
2026-10-06        0.0
2026-10-07      850.0
Freq: D, Name: Total_Venda, Length: 125, dtype: float64